import json
from pprint import pprint
import itertools

"""
0 ~ 11: Basic Orbs
12 ~ 14: Crafting
15 ~ 118: Essences
"""

action_dict = \
    {'0': 'Orb of Transmutation',
 '1': 'Orb of Alteration',
 '2': 'Orb of Agumentation',
 '3': 'Regal Orb',
 '4': 'Orb of Alchemy',
 '5': 'Chaos Orb',
 '6': 'Orb of Scouring',
 '7': 'Divine Orb',
 '8': 'Vaal Orb',
 '9': 'Orb of Annulment',
 '10': 'Veiled Chaos Orb',
 '11': 'Fracturing Orb',
 '12': 'Prefix Bench Crafting',
 '13': 'Suffix Bench Crafting',
 '14': 'Aisling Veil Crafting',
 '15': 'Muttering Essence of Anger',
 '16': 'Weeping Essence of Anger',
 '17': 'Wailing Essence of Anger',
 '18': 'Screaming Essence of Anger',
 '19': 'Shrieking Essence of Anger',
 '20': 'Deafening Essence of Anger',
 '21': 'Wailing Essence of Anguish',
 '22': 'Screaming Essence of Anguish',
 '23': 'Shrieking Essence of Anguish',
 '24': 'Deafening Essence of Anguish',
 '25': 'Whispering Essence of Contempt',
 '26': 'Muttering Essence of Contempt',
 '27': 'Weeping Essence of Contempt',
 '28': 'Wailing Essence of Contempt',
 '29': 'Screaming Essence of Contempt',
 '30': 'Shrieking Essence of Contempt',
 '31': 'Deafening Essence of Contempt',
 '32': 'Essence of Delirium',
 '33': 'Weeping Essence of Doubt',
 '34': 'Wailing Essence of Doubt',
 '35': 'Screaming Essence of Doubt',
 '36': 'Shrieking Essence of Doubt',
 '37': 'Deafening Essence of Doubt',
 '38': 'Screaming Essence of Dread',
 '39': 'Shrieking Essence of Dread',
 '40': 'Deafening Essence of Dread',
 '41': 'Screaming Essence of Envy',
 '42': 'Shrieking Essence of Envy',
 '43': 'Deafening Essence of Envy',
 '44': 'Muttering Essence of Fear',
 '45': 'Weeping Essence of Fear',
 '46': 'Wailing Essence of Fear',
 '47': 'Screaming Essence of Fear',
 '48': 'Shrieking Essence of Fear',
 '49': 'Deafening Essence of Fear',
 '50': 'Whispering Essence of Greed',
 '51': 'Muttering Essence of Greed',
 '52': 'Weeping Essence of Greed',
 '53': 'Wailing Essence of Greed',
 '54': 'Screaming Essence of Greed',
 '55': 'Shrieking Essence of Greed',
 '56': 'Deafening Essence of Greed',
 '57': 'Whispering Essence of Hatred',
 '58': 'Muttering Essence of Hatred',
 '59': 'Weeping Essence of Hatred',
 '60': 'Wailing Essence of Hatred',
 '61': 'Screaming Essence of Hatred',
 '62': 'Shrieking Essence of Hatred',
 '63': 'Deafening Essence of Hatred',
 '64': 'Essence of Horror',
 '65': 'Essence of Hysteria',
 '66': 'Essence of Insanity',
 '67': 'Wailing Essence of Loathing',
 '68': 'Screaming Essence of Loathing',
 '69': 'Shrieking Essence of Loathing',
 '70': 'Deafening Essence of Loathing',
 '71': 'Screaming Essence of Misery',
 '72': 'Shrieking Essence of Misery',
 '73': 'Deafening Essence of Misery',
 '74': 'Weeping Essence of Rage',
 '75': 'Wailing Essence of Rage',
 '76': 'Screaming Essence of Rage',
 '77': 'Shrieking Essence of Rage',
 '78': 'Deafening Essence of Rage',
 '79': 'Screaming Essence of Scorn',
 '80': 'Shrieking Essence of Scorn',
 '81': 'Deafening Essence of Scorn',
 '82': 'Muttering Essence of Sorrow',
 '83': 'Weeping Essence of Sorrow',
 '84': 'Wailing Essence of Sorrow',
 '85': 'Screaming Essence of Sorrow',
 '86': 'Shrieking Essence of Sorrow',
 '87': 'Deafening Essence of Sorrow',
 '88': 'Wailing Essence of Spite',
 '89': 'Screaming Essence of Spite',
 '90': 'Shrieking Essence of Spite',
 '91': 'Deafening Essence of Spite',
 '92': 'Weeping Essence of Suffering',
 '93': 'Wailing Essence of Suffering',
 '94': 'Screaming Essence of Suffering',
 '95': 'Shrieking Essence of Suffering',
 '96': 'Deafening Essence of Suffering',
 '97': 'Muttering Essence of Torment',
 '98': 'Weeping Essence of Torment',
 '99': 'Wailing Essence of Torment',
 '100': 'Screaming Essence of Torment',
 '101': 'Shrieking Essence of Torment',
 '102': 'Deafening Essence of Torment',
 '103': 'Whispering Essence of Woe',
 '104': 'Muttering Essence of Woe',
 '105': 'Weeping Essence of Woe',
 '106': 'Wailing Essence of Woe',
 '107': 'Screaming Essence of Woe',
 '108': 'Shrieking Essence of Woe',
 '109': 'Deafening Essence of Woe',
 '110': 'Weeping Essence of Wrath',
 '111': 'Wailing Essence of Wrath',
 '112': 'Screaming Essence of Wrath',
 '113': 'Shrieking Essence of Wrath',
 '114': 'Deafening Essence of Wrath',
 '115': 'Wailing Essence of Zeal',
 '116': 'Screaming Essence of Zeal',
 '117': 'Shrieking Essence of Zeal',
 '118': 'Deafening Essence of Zeal',
 }

file_path = 'json/actions_pool_2.json'

with open(file_path, 'w', encoding='utf-8') as file:
 json.dump(action_dict, file, indent='\t')